### ISSUE TITLE
What is the reason that LevelStore constructor factory function requires reference to express-session?

### ISSUE THREAD

**Issue by gajus** [tgohn/express-session-level#1]

**Comment by tgohn** [comment]
hey @gajus 

if I recall correctly, it's for getting a reference to `require('express-session').Store` and extend from it.
https://github.com/tgohn/express-session-level/blob/e3ab1225990c37f06aa9a2fa15b53d58d0d35669/index.js#L8

Similar to `connect-redis` https://github.com/tj/connect-redis/blob/3.1.0/lib/connect-redis.js#L39

**Comment by gajus** [comment]
Since `Store` is a constructor (and therefore immutable), would it make more sense to make `express-session` a peer dependency and require `require('express-session').Store` internally?

**Comment by tgohn** [comment]
yeah, you are right. I also thought the same thing when I worked on this module. :smile: 

However, I decided to follow other implementations in the end. Follow the norm.
